### ISSUE TITLE
Possibility to export to different frameworks (?)

### ISSUE THREAD

**Issue by hugocxl** [kerwanp/notion-renderer#1]
Hi @kerwanp. Amazing work here. Love the concept and the approach ❤️

I was wondering if you had in mind the possibility to use the core of the lib to translate into different frameworks: React, Vue, etc. apart from pure HTML. 
If so, I'm glad to help on the React adapter.

Thanks!

**Comment by kerwanp** [comment]
Hi @hugocxl, thanks for your feedback! Sorry for the 2 weeks delay, I was on vacation 😄 

I am currently working on a big refactor of this library to improve the usage of the result by integrating in the https://github.com/unifiedjs/unified ecosystem. The idea is to give the ability to use all the Remark and Rehype plugins for HTML and Markdown.

Anyway I'm definitely open to PR if you want to build some kind of wrapper! Feel free to ping me on Discord if you have any question to get started. "kerwan."
